name: Daily Dev Log Commit

on:
  schedule:
    - cron: "0 13 * * *"  # runs daily at 9 AM EST
  workflow_dispatch:

permissions:
  contents: write

jobs:
  daily-log:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Create daily log if missing
        run: |
          TODAY=$(date -u +'%Y-%m-%d')
          FILE="logs/${TODAY}.md"
          if [ ! -f "$FILE" ]; then
            mkdir -p logs
            echo "# ${TODAY}" > "$FILE"
            echo "- Auto-log entry: No commits yet today." >> "$FILE"
            git add "$FILE"
            git commit -m "Add daily auto-log for ${TODAY}"
            git push
          else
            echo "Log for ${TODAY} already exists. Skipping."
          fi
